### ISSUE TITLE
Armhf build of latest Leia headless

### ISSUE THREAD

**Issue by mammo0** [linuxserver-archive/docker-kodi-headless-armhf#13]
Hello,

can you please provide an **armhf** build of the latest headless Leia release in the main repo ([docker-kodi-headless](https://github.com/linuxserver/docker-kodi-headless))? Like the [arm64](https://github.com/linuxserver/docker-kodi-headless-arm64) build?

Thank you very much!

**Comment by sparklyballs** [comment]
working on it, hold tight though because it takes HOURS to build and sometimes the failures are at the end of each run.

**Comment by mammo0** [comment]
Ok, thx for the information!

**Comment by sparklyballs** [comment]
i can't get it to build with the Leia branch, and i've spent enough time on it.

**Comment by mammo0** [comment]
Maybe I can help you because meanwhile I fond a working solution. Please have a look at my fork: https://github.com/mammo0/docker-kodi-headless-armhf

You may ignore the additional installation of ffmpeg from the Ubuntu cosmic sources. I've done this to speed up the build process because building ffmpeg along with Kodi takes a lot of time... But the disadvantage is that the image size increased to about 500MB. So for a smaller image it would be better to build ffmpeg along with Kodi.

You can also ignore the `Dockerfile.crosscompile` file. This file is just for me that I don't have to build Kodi on my RPi.

**Comment by mammo0** [comment]
I had a look at your personal fork of this repo and I think that the main difference between our Dockerfiles are the following two lines:
```
-DCMAKE_C_FLAGS="-march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=hard -mvectorize-with-neon-quad"
-DCMAKE_CXX_FLAGS="-march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=hard -mvectorize-with-neon-quad"
```
I've added these two lines to the cmake call because I had a build error (don't know the exactly error right now). After a bit of searching I found out that Kodi itself uses these C(XX)_FLAGS when building for RPi (see [ArchSetup.cmake](https://github.com/xbmc/xbmc/blob/adf1da5c461a4c10bae5858d89e75d86d641bedf/cmake/scripts/linux/ArchSetup.cmake#L44)). After I added the flags the build process was succeeded.

I hope that helps you!

**Comment by sparklyballs** [comment]
thanks @mammo0 , that was the secret sauce required.

**Comment by mammo0** [comment]
I'm glad that I could help you :)

**Comment by mr-honest** [comment]
Hi @mammo0 and @sparklyballs 
As I have media centers running MrMC on ATV4k (krypton DB) and kodi on standalones players (leia DB), I need to be able to download krypton version also in ARMHF. However I cannot download armhf version of krypton, when using "krypton" tag. This only works for the docker image for x86. 
Is it possible to download the image for kodi krypton 17.6 headless? 

Thank you both
