### ISSUE TITLE
Rebase to Ubuntu Bionic?

### ISSUE THREAD

**Issue by matthuisman** [linuxserver-archive/docker-kodi-headless-armhf#8]
When using this container on Odroid XU4, I get an error (and crash) as soon as I try to list my movies or TV Shows.
Everything else works fine (updates etc).

The error in the log is:
```
14:10:07.593 T:2787111920   DEBUG: CWebServer [MHD]: Not enough memory to allocate header record!
14:10:07.593 T:2787111920   DEBUG: CWebServer [MHD]: Error 413 (`<html><head><title>Request too big</title></head><body>Your HTTP header was too big for the memory constraints of this webserver.</body></html>') processing request, closing connection.
14:10:07.593 T:2787111920   DEBUG: CWebServer [MHD]: Not enough memory for write!
14:10:07.593 T:2787111920   DEBUG: CWebServer [MHD]: Closing connection (failed to create response header)
```
MHD = microhttpd

When I build a headless KODI in Arch Linux, it works fine.

I see that Arch uses libmicrohttpd 0.9.59
Ubuntu Xenial uses libmicrohttpd 0.9.44
Ubuntu Bionic uses libmicrohttpd 0.9.59

Maybe in the later versions they have increased the memory size limit?

**Comment by adelolmo** [comment]
I experienced the same behavior but sadly without the log error.
I tested it using bionic as @matthuisman suggested and the issue seems to disappear.

**Comment by matthuisman** [comment]
I also built using Bionic (as well as arch) and it worked fine :+1: 
I had to have extralogging on for that error to show up.
